# Generated by Django 6.0.5 on 2026-05-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('none', 'Sin pago'), ('redsys_test', 'Redsys TEST')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendiente de pago'), ('paid', 'Pagado'), ('failed', 'Pago fallido'), ('cancelled', 'Pago cancelado')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='redsys_order',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='redsys_response_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
